### ISSUE TITLE
Readme most wanted

### ISSUE THREAD

**Issue by toothfairy** [jgorset/lean-coffee#2]
![screen shot 2015-03-13 at 18 44 45](https://cloud.githubusercontent.com/assets/725806/6644005/1449f35c-c9b1-11e4-99c5-a52ba2b2407d.png)

**Comment by timkurvers** [comment]
:heart:

**Comment by jgorset** [comment]
Ha ha.

**Comment by jgorset** [comment]
I fix dis in https://github.com/jgorset/lean-coffee/commit/651c6fd78e5825ad15c2eb55e8ae3b15e1ac321c!
