### ISSUE TITLE
Sorting issues doesn't push to other clients

### ISSUE THREAD

**Issue by sindrenm** [jgorset/lean-coffee#6]
When sorting issues by votes on one client, this doesn't seem to push out to the other clients, which it probably should. :wink:

**Comment by jgorset** [comment]
Haha, thanks @sindrenm. ;-)

**Comment by sindrenm** [comment]
Don't know why I called them “issues”, though. Must've been in JIRA land.

**Comment by richardtop** [comment]
Why not to perform sorting on the client side?

**Comment by sindrenm** [comment]
Actually, you should totally move the entire database to Firebase. That fixes your life.
