### ISSUE TITLE
Storing old sessions

### ISSUE THREAD

**Issue by ohenrik** [jgorset/lean-coffee#7]
I was thinking it might be smart to create different sessions. So that we can store old notes and see what we talked about when. 

So maybe create a sessions model that topics belongs to. This way we can for example refer to a previous session based on date.

**Comment by timkurvers** [comment]
Awesome idea! :+1:

**Comment by ohenrik** [comment]
:tada:

**Comment by timkurvers** [comment]
Heh! :smile:

**Comment by jgorset** [comment]
:+1:

**Comment by jgorset** [comment]
Maybe what we could do is just allow entering an arbitrary path (like `http://domain.com/my-session`) to create and/or load an existing session. Pretty simple interface.

**Comment by ohenrik** [comment]
Thats a good idea. :) Hover i think we need to restructure the front and back end a bit. I started on this a while ago, but felt i needed to restructure quite allot. Also we need to alter the design to let users switch sessions easily.

**Comment by jgorset** [comment]
Sure, but to start I think just entering something in the path to make your own session would do fine!
