### ISSUE TITLE
Status code on update

### ISSUE THREAD

**Issue by timkurvers** [jgorset/lean-coffee#8]
Should [this](https://github.com/jgorset/lean-coffee/blob/master/app/controllers/topics_controller.rb#L36-L52) be `:accepted` or `:ok` instead?

``` ruby
def update
  respond_to do |format|
    if @topic.save
      push_updated_topic @topic

      format.html { redirect_to topics_path }
      format.json { render 'show', status: :created }
    end
  end
end
```

**Comment by jgorset** [comment]
You don't think `HTTP 201 Created` makes sense? I think `HTTP 202 Accepted` means that processing has not been completed, and `HTTP 200 OK` is just generic when there's nothing more apprioriate to say.

**Comment by timkurvers** [comment]
On update?

**Comment by timkurvers** [comment]
Sorry for the tiny message, was on my phone.

According to http://stackoverflow.com/questions/2342579/http-status-code-for-update-and-delete we should probably be using `200 OK` or `204 No Content` for updates instead.

**Comment by jgorset** [comment]
ohh, this is on `update` — my bad, @timkurvers, I thought it was on `create`.
