### ISSUE TITLE
Backend should be in charge of voting

### ISSUE THREAD

**Issue by timkurvers** [jgorset/lean-coffee#9]
Instead of allowing `votes` to be tweaked directly by `PATCH /topics/x` requests, we should consider adding `vote` and `unvote` endpoints (or something similar):

```
POST /topics/x/vote
POST /topics/x/unvote
```

This would make voting an atomic operation (hopefully :smile:) and fix the issues we encountered during the team meeting today.

**Comment by ohenrik** [comment]
I was just about to add this as an issue myself. I'll try to solve this tonight when I'm building the sessions logic. :)

**Comment by jgorset** [comment]
Definitely, @timkurvers – somehow it never struck me that this wasn't atomic and would probably break when lots of people started voting on the same things at once. :-)

**Comment by jgorset** [comment]
Also I like @ohenrik.

**Comment by ohenrik** [comment]
:+1:
